excluded:
  - Pods
  - Vaion

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - fatal_error_message
  - first_where
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - function_default_parameter_at_end
  - fallthrough
  - array_init
  - contains_over_first_not_nil

type_name:
    min_length: 2
    max_length: 50

disabled_rules:
  - function_body_length
  - file_length
  - type_body_length
  - function_parameter_count
  - nesting

identifier_name:
  excluded:
    - id
    - on
    - to
    - qr
    - x
    - y

allow_zero_lintable_files: true
